import type { Term } from './types';

export const categories = [
  '통화·서비스',
  'SIP 메시지',
  'IMS·네트워크',
  '미디어·코덱',
  'SIM·단말',
  '품질·화질',
];

type TermSeed = [
  id: string,
  term: string,
  fullName: string,
  category: Term['category'],
  simple: string,
  practical: string,
  example: string,
];

const termSeeds: TermSeed[] = [
  [
    'video-call',
    '영상통화',
    'Video Call',
    '통화·서비스',
    '음성과 영상을 동시에 주고받는 실시간 통화 서비스예요.',
    '통화 연결 여부뿐 아니라 양방향 음성, 영상 해상도, 프레임 유지, 화면 전환을 함께 확인합니다.',
    '통화 연결 후 두 단말의 영상과 음성이 모두 정상적으로 전달되는지 확인합니다.',
  ],
  [
    'voice-call',
    '음성통화',
    'Voice Call',
    '통화·서비스',
    '두 사용자가 음성으로 대화할 수 있도록 연결하는 통신 서비스예요.',
    '발신·수신·연결·종료 흐름과 양방향 음질, 지연, 끊김 여부를 확인합니다.',
    '수신자가 전화를 받은 뒤 양쪽에서 음성이 정상적으로 들리는지 확인합니다.',
  ],
  [
    'volte',
    'VoLTE',
    'Voice over LTE',
    '통화·서비스',
    'LTE 데이터망과 IMS를 이용해 음성통화를 제공하는 기술이에요.',
    '단말의 IMS 등록 상태와 SIP 호 처리, 전용 베어러 생성 여부를 함께 확인합니다.',
    'LTE 상태에서 발신한 뒤 IMS 등록과 통화 연결이 정상인지 확인합니다.',
  ],
  [
    'dtmf',
    'DTMF',
    'Dual-Tone Multi-Frequency',
    '통화·서비스',
    '전화 키패드의 숫자와 기호를 두 개의 주파수 조합으로 전달하는 신호 방식이에요.',
    '통화 중 0~9, 별표, 우물정자를 입력했을 때 상대 시스템이 정확히 인식하는지 확인합니다.',
    'ARS 연결 후 1번을 눌러 해당 메뉴로 이동하는지 확인합니다.',
  ],
  [
    'sms',
    'SMS',
    'Short Message Service',
    '통화·서비스',
    '이동통신망에서 짧은 문자 메시지를 주고받는 서비스예요.',
    '통화 중에도 메시지 발신과 수신이 가능하고 내용이 손상되지 않는지 확인합니다.',
    '영상통화 중 다른 단말에서 SMS를 보내 정상 수신되는지 확인합니다.',
  ],
  [
    'mms',
    'MMS',
    'Multimedia Messaging Service',
    '통화·서비스',
    '문자뿐 아니라 사진·영상 등 멀티미디어를 전송하는 메시지 서비스예요.',
    '망 상태와 통화 상태가 바뀌어도 첨부 파일과 본문이 정상적으로 전달되는지 확인합니다.',
    '영상통화 중 사진이 포함된 MMS를 발신하고 수신 결과를 확인합니다.',
  ],
  [
    'sip',
    'SIP',
    'Session Initiation Protocol',
    'SIP 메시지',
    '멀티미디어 통신 세션을 만들고 변경하고 종료하는 시그널링 프로토콜이에요.',
    '단말 등록, 통화 발신, 응답 코드, 세션 갱신 등 호 처리 흐름을 메시지 단위로 확인합니다.',
    '통화 발신 시 INVITE가 전송되고 응답 메시지가 순서대로 수신되는지 확인합니다.',
  ],
  [
    'register',
    'REGISTER',
    'SIP REGISTER Request',
    'SIP 메시지',
    '단말의 현재 접속 위치와 주소를 SIP 서버에 등록하는 요청 메시지예요.',
    '전원 켜기나 비행기 모드 해제 후 REGISTER와 인증 응답, 최종 성공 응답을 확인합니다.',
    'REGISTER → 401 Unauthorized → REGISTER → 200 OK 순서로 등록되는지 확인합니다.',
  ],
  [
    'subscribe',
    'SUBSCRIBE',
    'SIP SUBSCRIBE Request',
    'SIP 메시지',
    '특정 상태나 이벤트가 바뀔 때 알림을 받기 위해 구독을 요청하는 메시지예요.',
    'Event와 Accept 헤더가 예상한 값으로 구성되는지 확인합니다.',
    'IMS 등록 후 SUBSCRIBE 메시지의 Event 값이 reg인지 확인합니다.',
  ],
  [
    'invite',
    'INVITE',
    'SIP INVITE Request',
    'SIP 메시지',
    '새 통화를 시작하거나 진행 중인 세션 조건을 변경할 때 보내는 요청이에요.',
    '수신 주소, 발신 정보, SDP, 세션 타이머가 요구사항에 맞는지 확인합니다.',
    '영상통화 발신 시 INVITE 안에 영상 코덱 정보가 포함되는지 확인합니다.',
  ],
  [
    '200-ok',
    '200 OK',
    'SIP 200 OK Response',
    'SIP 메시지',
    '요청이 정상적으로 처리되었다는 SIP 성공 응답이에요.',
    'REGISTER 성공, INVITE 수락 등 어떤 요청에 대한 응답인지 CSeq와 함께 확인합니다.',
    'REGISTER 재전송 후 200 OK가 수신되어 IMS 등록이 완료되는지 확인합니다.',
  ],
  [
    '401-unauthorized',
    '401 Unauthorized',
    'SIP 401 Unauthorized Response',
    'SIP 메시지',
    '서버가 단말에 인증 정보를 요구할 때 보내는 응답이에요.',
    '첫 REGISTER 뒤 401을 받은 단말이 인증 값을 포함해 REGISTER를 다시 보내는지 확인합니다.',
    '401 수신 후 인증 정보가 포함된 REGISTER가 재전송되는지 확인합니다.',
  ],
  [
    '489-bad-event',
    '489 Bad Event',
    'SIP 489 Bad Event Response',
    'SIP 메시지',
    '서버가 SUBSCRIBE에 지정된 이벤트를 지원하지 않을 때 보내는 응답이에요.',
    'SUBSCRIBE의 Event 값과 서버 응답이 예상한 시나리오와 일치하는지 확인합니다.',
    'SUBSCRIBE 전송 후 489 Bad Event가 수신되는지 확인합니다.',
  ],
  [
    '603-decline',
    '603 Decline',
    'SIP 603 Decline Response',
    'SIP 메시지',
    '수신 측이 통화 요청을 명확하게 거절했음을 나타내는 응답이에요.',
    '거절 시 발신 화면의 안내 문구와 통화 종료 동작이 규격에 맞는지 확인합니다.',
    '수신자가 거절 버튼을 누르면 603 응답과 안내 문구가 발생하는지 확인합니다.',
  ],
  [
    '480-response',
    '480 Response',
    'SIP 480 Temporarily Unavailable',
    'SIP 메시지',
    '상대방이 현재 일시적으로 통화할 수 없는 상태임을 나타내는 응답이에요.',
    '배터리나 단말 상태 등 시나리오에 따라 안내 문구와 종료 처리가 맞는지 확인합니다.',
    '상대 단말이 통화 불가 상태일 때 480 응답 후 발신이 종료되는지 확인합니다.',
  ],
  [
    '486-user-busy',
    '486 User Busy',
    'SIP 486 Busy Here Response',
    'SIP 메시지',
    '상대방이 다른 통화 중이라 현재 요청을 받을 수 없다는 응답이에요.',
    '통화 중인 단말로 발신했을 때 응답 코드와 사용자 안내가 일치하는지 확인합니다.',
    '상대방 통화 중 발신 시 486 응답과 통화 중 안내가 표시되는지 확인합니다.',
  ],
  [
    '491-glare',
    '491 Glare Condition',
    'SIP 491 Request Pending Response',
    'SIP 메시지',
    '같은 세션에서 처리 중인 요청과 새 요청이 충돌했음을 나타내는 응답이에요.',
    '동시에 세션 변경 요청이 발생해도 기존 통화가 안정적으로 유지되는지 확인합니다.',
    '491 응답이 발생한 뒤 영상통화가 끊기지 않고 유지되는지 확인합니다.',
  ],
  [
    '408-timeout',
    '408 Request Timeout',
    'SIP 408 Request Timeout Response',
    'SIP 메시지',
    '정해진 시간 안에 요청에 대한 응답을 받지 못했음을 나타내는 응답이에요.',
    '무응답 시 타이머 만료, 안내 문구, 자동 종료 시점이 규격과 맞는지 확인합니다.',
    '상대방이 받지 않을 때 408 응답과 부재 안내가 표시되는지 확인합니다.',
  ],
  [
    'session-update',
    'Session Update',
    'SIP Session Update',
    'SIP 메시지',
    '진행 중인 통화의 세션 정보를 주기적으로 갱신하는 동작이에요.',
    'Session-Expires 값을 기준으로 정해진 시점에 갱신 메시지가 발생하는지 확인합니다.',
    '장시간 영상통화 중 세션 갱신 메시지가 한 번 이상 정상 발생하는지 확인합니다.',
  ],
  [
    'ims',
    'IMS',
    'IP Multimedia Subsystem',
    'IMS·네트워크',
    'IP망에서 음성·영상통화와 멀티미디어 서비스를 제어하는 통신망 구조예요.',
    '단말이 IMS에 등록되어야 VoLTE와 영상통화의 SIP 호 처리가 진행됩니다.',
    '통화 전 단말의 IMS 등록 상태가 정상인지 확인합니다.',
  ],
  [
    'pcscf',
    'P-CSCF',
    'Proxy-Call Session Control Function',
    'IMS·네트워크',
    '단말이 IMS에 접속할 때 처음 만나는 SIP 프록시 기능이에요.',
    'REGISTER와 INVITE가 설정된 P-CSCF 주소와 포트로 전송되는지 확인합니다.',
    '히든 메뉴의 P-CSCF 주소와 실제 SIP 전송 목적지가 일치하는지 확인합니다.',
  ],
  [
    'p-access-network-info',
    'P-Access-Network-Info',
    'SIP P-Access-Network-Info Header',
    'IMS·네트워크',
    '단말이 접속한 무선망 종류와 망 식별 정보를 전달하는 SIP 헤더예요.',
    '3GPP-E-UTRAN, MCC, MNC, 셀 식별 정보가 요구 형식에 맞는지 확인합니다.',
    'REGISTER와 SUBSCRIBE의 P-Access-Network-Info 값을 비교합니다.',
  ],
  [
    'dns-query',
    'DNS Query',
    'Domain Name System Query',
    'IMS·네트워크',
    '도메인 이름에 대응하는 IP 주소를 찾기 위한 질의예요.',
    'DNS 질의가 실패했을 때 저장된 P-CSCF나 최신 망 설정으로 재접속하는지 확인합니다.',
    'DNS 실패 후 단말이 대체 P-CSCF로 REGISTER를 시도하는지 확인합니다.',
  ],
  [
    'pdn',
    'PDN',
    'Packet Data Network',
    'IMS·네트워크',
    '이동통신 단말이 접속하는 외부 패킷 데이터 네트워크예요.',
    '일반 통화와 긴급통화에서 IMS PDN 또는 긴급 PDN으로 전환되는지 확인합니다.',
    '긴급 영상통화 전후에 PDN 연결 상태가 예상한 순서로 바뀌는지 확인합니다.',
  ],
  [
    'eps-bearer',
    'EPS Bearer',
    'Evolved Packet System Bearer',
    'IMS·네트워크',
    'LTE 망에서 단말과 네트워크 사이의 데이터 전달 경로를 논리적으로 구분한 단위예요.',
    '통화 시작과 종료 시 기본 또는 전용 베어러가 생성·해제되는지 확인합니다.',
    '영상통화 연결 시 필요한 EPS bearer가 활성화되는지 확인합니다.',
  ],
  [
    'dedicated-bearer',
    'Dedicated Bearer',
    'Dedicated EPS Bearer',
    'IMS·네트워크',
    '특정 서비스 품질을 보장하기 위해 별도로 설정하는 EPS 전달 경로예요.',
    '음성·영상통화 연결 시 서비스에 맞는 전용 베어러와 QCI가 할당되는지 확인합니다.',
    '영상통화 시작 후 Dedicated Bearer가 생성되고 종료 후 해제되는지 확인합니다.',
  ],
  [
    'qci',
    'QCI',
    'QoS Class Identifier',
    'IMS·네트워크',
    'LTE에서 지연, 우선순위 등 서비스 품질 특성을 구분하는 식별 값이에요.',
    '음성이나 영상 미디어에 요구되는 QCI가 전용 베어러에 정확히 할당되는지 확인합니다.',
    '영상통화 연결 시 음성과 영상에 대응하는 QCI 값이 생성되는지 확인합니다.',
  ],
  [
    'rsrp',
    'RSRP',
    'Reference Signal Received Power',
    'IMS·네트워크',
    'LTE 기준 신호의 수신 전력을 나타내는 무선 품질 지표예요.',
    '값이 낮은 약전계 환경에서 통화 끊김과 영상 품질 저하 여부를 확인합니다.',
    'RSRP가 -120 dBm 이하인 환경에서 영상통화가 유지되는지 확인합니다.',
  ],
  [
    'sdp',
    'SDP',
    'Session Description Protocol',
    '미디어·코덱',
    '멀티미디어 세션에서 사용할 매체, 주소, 포트, 코덱 조건을 기술하는 프로토콜이에요.',
    'INVITE의 SDP에서 음성·영상 포트, Payload Type, 코덱, 비트레이트 속성을 확인합니다.',
    'INVITE와 응답 SDP의 코덱 구성이 서로 호환되는지 확인합니다.',
  ],
  [
    'rtp',
    'RTP',
    'Real-Time Transport Protocol',
    '미디어·코덱',
    '실시간 음성과 영상 데이터를 전달하기 위한 전송 프로토콜이에요.',
    '통화가 연결된 뒤 실제 미디어 패킷이 양방향으로 전송되는지 확인합니다.',
    '영상통화 중 RTP 패킷의 코덱과 페이로드 구성을 확인합니다.',
  ],
  [
    'dynamic-payload-type',
    'Dynamic Payload Type',
    'RTP Dynamic Payload Type',
    '미디어·코덱',
    '세션마다 코덱과 RTP 번호의 대응 관계를 동적으로 지정하는 방식이에요.',
    'SDP의 rtpmap 값과 실제 RTP 패킷의 Payload Type이 일치하는지 확인합니다.',
    'SDP에서 112번이 H.265로 협상됐다면 RTP에도 같은 값이 사용되는지 확인합니다.',
  ],
  [
    'evs',
    'EVS',
    'Enhanced Voice Services',
    '미디어·코덱',
    '이동통신에서 고품질 음성을 제공하기 위한 광대역 음성 코덱이에요.',
    '지원 단말의 SDP에 EVS가 포함되고 실제 통화에서 정상 협상되는지 확인합니다.',
    'EVS 지원 단말끼리 통화할 때 SDP의 EVS/16000 항목을 확인합니다.',
  ],
  [
    'amr-wb',
    'AMR-WB',
    'Adaptive Multi-Rate Wideband',
    '미디어·코덱',
    '넓은 음성 대역을 사용하는 이동통신용 광대역 음성 코덱이에요.',
    'EVS를 사용할 수 없을 때 AMR-WB로 정상 대체 협상되는지 확인합니다.',
    'SDP의 AMR-WB/16000 항목과 통화 음질을 확인합니다.',
  ],
  [
    'amr-nb',
    'AMR-NB',
    'Adaptive Multi-Rate Narrowband',
    '미디어·코덱',
    '좁은 음성 대역을 사용하는 이동통신용 음성 코덱이에요.',
    '망이나 상대 단말 조건에 따라 AMR 계열 코덱으로 대체되는지 확인합니다.',
    'SDP에서 AMR/8000 항목이 협상되는 시나리오를 확인합니다.',
  ],
  [
    'h263',
    'H.263',
    'ITU-T H.263 Video Coding',
    '미디어·코덱',
    '낮은 전송률의 영상통신에 사용되는 영상 압축 표준이에요.',
    '구형 또는 3G 영상통화 단말과의 호환성에서 SDP 지원 여부를 확인합니다.',
    'H.263 단말과 통화할 때 영상 연결과 화질이 정상인지 확인합니다.',
  ],
  [
    'h264',
    'H.264',
    'Advanced Video Coding',
    '미디어·코덱',
    '영상 데이터를 효율적으로 압축하는 널리 사용되는 영상 코덱이에요.',
    'SDP의 profile, level, packetization mode와 영상 비트레이트를 확인합니다.',
    'H.264 영상통화에서 목표 비트레이트 이상으로 영상이 전송되는지 확인합니다.',
  ],
  [
    'h265',
    'H.265',
    'High Efficiency Video Coding',
    '미디어·코덱',
    'H.264보다 높은 압축 효율을 목표로 하는 고효율 영상 코덱이에요.',
    '지원 단말의 SDP에 H.265가 포함되고 고화질 영상통화로 연결되는지 확인합니다.',
    'H.265 단말끼리 연결했을 때 720p급 영상과 목표 비트레이트를 확인합니다.',
  ],
  [
    'frame-bundling',
    'Frame Bundling',
    'RTP Frame Bundling',
    '미디어·코덱',
    '여러 미디어 프레임을 하나의 전송 단위에 묶어 보내는 방식이에요.',
    'RTP 패킷에 포함된 프레임 수와 시간 간격이 협상 조건에 맞는지 확인합니다.',
    'EVS 통화의 RTP 패킷에서 프레임 묶음 구성을 확인합니다.',
  ],
  [
    'candidate-attribute',
    'Candidate Attribute',
    'SDP Candidate Attribute',
    '미디어·코덱',
    '미디어 연결에 사용할 수 있는 IP 주소와 포트 후보를 표현하는 SDP 속성이에요.',
    'candidate 번호, component ID, transport, priority, IP, port, type 구성을 확인합니다.',
    'SDP의 candidate 항목에 주소와 포트가 빠짐없이 포함되는지 확인합니다.',
  ],
  [
    'sim',
    'SIM',
    'Subscriber Identity Module',
    'SIM·단말',
    '이동통신 가입자 식별 정보를 저장하는 모듈이에요.',
    '통화·문자·데이터에 사용할 SIM 선택과 망 등록 상태를 확인합니다.',
    '두 개의 SIM이 있는 단말에서 발신 SIM과 데이터 SIM 설정을 확인합니다.',
  ],
  [
    'esim',
    'eSIM',
    'Embedded SIM',
    'SIM·단말',
    '단말에 내장되어 프로파일을 내려받아 사용하는 디지털 SIM 방식이에요.',
    'eSIM과 물리 SIM을 함께 사용할 때 통화 수신과 데이터 전환 동작을 확인합니다.',
    'eSIM으로 영상통화 중 다른 SIM으로 들어오는 통화 처리 결과를 확인합니다.',
  ],
  [
    'usim',
    'USIM',
    'Universal Subscriber Identity Module',
    'SIM·단말',
    '3세대 이후 이동통신에서 가입자 인증과 서비스 정보를 제공하는 범용 SIM이에요.',
    'USIM 교체 후 망 등록, 통화, 메시지, 가입 서비스가 정상인지 확인합니다.',
    '다른 요금제가 설정된 USIM으로 교체한 뒤 영상통화를 확인합니다.',
  ],
  [
    'uicc',
    'UICC',
    'Universal Integrated Circuit Card',
    'SIM·단말',
    'SIM·USIM 같은 통신 애플리케이션을 담는 범용 집적 회로 카드예요.',
    '카드 이동 후 단말이 가입자 정보를 다시 읽고 IMS에 정상 등록되는지 확인합니다.',
    'UICC를 다른 단말로 옮긴 뒤 영상통화가 정상 동작하는지 확인합니다.',
  ],
  [
    'dsds',
    'DSDS',
    'Dual SIM Dual Standby',
    'SIM·단말',
    '두 개의 SIM을 대기 상태로 유지하고 필요할 때 하나를 사용하도록 하는 방식이에요.',
    '음성·메시지·데이터 기본 SIM 조합에 따라 영상통화 수발신이 정상인지 확인합니다.',
    'SIM A와 SIM B의 망 모드를 다르게 설정한 뒤 각각 영상통화를 확인합니다.',
  ],
  [
    'mep',
    'MEP',
    'Multiple Enabled Profiles',
    'SIM·단말',
    '여러 eSIM 프로파일을 동시에 활성화할 수 있도록 하는 기능이에요.',
    'MEP 지원 단말에서 eSIM 프로파일 조합별 통화와 데이터 동작을 확인합니다.',
    'eSIM1과 eSIM2를 함께 활성화한 상태에서 영상통화 수발신을 확인합니다.',
  ],
  [
    'ipsec',
    'IPsec',
    'Internet Protocol Security',
    'SIM·단말',
    'IP 패킷을 인증하고 암호화해 안전하게 전달하는 보안 기술 모음이에요.',
    'IMS 접속 보안이 적용된 단말과 미적용 단말 사이의 호환성을 확인합니다.',
    'IPsec 지원 단말과 영상통화 연결이 정상적으로 유지되는지 확인합니다.',
  ],
  [
    'mvno',
    'MVNO',
    'Mobile Virtual Network Operator',
    'SIM·단말',
    '자체 무선망 없이 다른 이동통신사의 망을 빌려 서비스를 제공하는 사업자예요.',
    '알뜰폰 SIM을 장착했을 때 IMS 등록과 음성·영상통화 호환성을 확인합니다.',
    'MVNO SIM으로 영상통화 수발신이 정상인지 확인합니다.',
  ],
  [
    'video-bitrate',
    'Video Bitrate',
    'Video Data Rate',
    '품질·화질',
    '1초 동안 전송되는 영상 데이터의 양을 나타내는 값이에요.',
    '코덱과 망 조건에 따라 영상 비트레이트가 기준 이상으로 유지되는지 확인합니다.',
    'H.265 영상통화에서 비트레이트가 목표 기준 이상인지 확인합니다.',
  ],
  [
    'vga',
    'VGA',
    'Video Graphics Array',
    '품질·화질',
    '일반적으로 640×480 픽셀 해상도를 가리키는 영상 규격이에요.',
    '특정 영상통화 시나리오에서 요구되는 화면 크기와 실제 전송 해상도를 확인합니다.',
    '긴급 영상통화가 VGA급 화면으로 연결되는지 확인합니다.',
  ],
  [
    'qcif',
    'QCIF',
    'Quarter Common Intermediate Format',
    '품질·화질',
    '낮은 전송률 영상통화에 쓰이는 176×144 픽셀급 영상 형식이에요.',
    '3G 영상통화 등 제한된 환경에서 협상된 해상도와 화면 품질을 확인합니다.',
    '3G 긴급 영상통화가 QCIF급으로 연결되는지 확인합니다.',
  ],
];

export const terms: Term[] = termSeeds.map(
  ([id, term, fullName, category, simple, practical, example]) => ({
    id,
    term,
    fullName,
    category,
    simple,
    practical,
    example,
  }),
);

export interface BlockQuiz {
  id: string;
  title: string;
  category: string;
  description: string;
  xp: number;
  blocks: Array<{
    id: string;
    label: string;
  }>;
}

export const blockQuizzes: BlockQuiz[] = [
  {
    id: 'ims-register-flow',
    title: 'IMS 등록 동작 확인',
    category: 'SIP',
    description:
      '단말이 IMS망에 등록될 때 발생하는 메시지 흐름을 순서대로 조합합니다.',
    xp: 30,
    blocks: [
      {
        id: 'ims-connect-tool',
        label: '단말을 로그 확인 도구에 연결한다.',
      },
      {
        id: 'ims-toggle-network',
        label: '비행기 모드를 켰다가 끄거나 단말 전원을 다시 켠다.',
      },
      {
        id: 'ims-first-register',
        label: '단말이 인증 정보가 없는 REGISTER를 전송한다.',
      },
      {
        id: 'ims-401',
        label: '서버에서 401 Unauthorized를 수신한다.',
      },
      {
        id: 'ims-second-register',
        label: '단말이 인증 정보를 포함한 REGISTER를 다시 전송한다.',
      },
      {
        id: 'ims-200-subscribe',
        label: '200 OK 수신 후 SUBSCRIBE와 후속 응답을 확인한다.',
      },
    ],
  },
  {
    id: 'video-call-basic',
    title: '영상통화 수발신 확인',
    category: '기본동작',
    description:
      '두 단말 사이에서 영상통화를 연결하고 화면과 음질을 확인하는 기본 TC입니다.',
    xp: 20,
    blocks: [
      {
        id: 'basic-prepare',
        label: '시험용 단말 A와 B의 통신 상태를 확인한다.',
      },
      {
        id: 'basic-dial',
        label: 'A단말에서 B단말 번호를 입력하고 영상통화를 발신한다.',
      },
      {
        id: 'basic-answer',
        label: 'B단말에서 영상통화를 수신한다.',
      },
      {
        id: 'basic-media',
        label: '양쪽 단말의 영상 화면과 통화 음질을 확인한다.',
      },
      {
        id: 'basic-end',
        label: '영상통화를 종료하고 통화 종료 상태를 확인한다.',
      },
    ],
  },
  {
    id: 'video-call-reject',
    title: '영상통화 수신 거절 확인',
    category: '호처리',
    description:
      '수신 단말이 영상통화를 거절했을 때 SIP 응답과 발신 화면을 확인합니다.',
    xp: 20,
    blocks: [
      {
        id: 'reject-connect-tool',
        label: '수신 단말 A를 로그 확인 도구에 연결한다.',
      },
      {
        id: 'reject-call',
        label: 'B단말에서 A단말로 영상통화를 발신한다.',
      },
      {
        id: 'reject-action',
        label: 'A단말의 수신 화면에서 거절을 선택한다.',
      },
      {
        id: 'reject-message',
        label: 'A단말에서 603 Decline 메시지가 전송되는지 확인한다.',
      },
      {
        id: 'reject-ui',
        label: 'B단말에 안내 문구가 표시되고 통화가 종료되는지 확인한다.',
      },
    ],
  },
  {
    id: 'dedicated-bearer',
    title: 'Dedicated Bearer 동작 확인',
    category: '네트워크',
    description:
      '영상통화 연결과 종료에 따라 전용 베어러가 생성·해제되는 흐름을 확인합니다.',
    xp: 30,
    blocks: [
      {
        id: 'bearer-connect-tool',
        label: 'A단말을 로그 확인 도구에 연결한다.',
      },
      {
        id: 'bearer-idle',
        label: 'IDLE 상태에서 2분 이상 대기한다.',
      },
      {
        id: 'bearer-call',
        label:
          'A단말에서 B단말로 영상통화를 발신하고 B단말에서 수신한다.',
      },
      {
        id: 'bearer-create',
        label:
          '영상통화 연결 후 Dedicated EPS Bearer 생성 메시지를 확인한다.',
      },
      {
        id: 'bearer-qci',
        label: '영상통화에 QCI 1과 QCI 2가 할당되는지 확인한다.',
      },
      {
        id: 'bearer-release',
        label: '통화 종료 후 EPS Bearer 해제 메시지를 확인한다.',
      },
    ],
  },
  {
    id: 'video-call-mute',
    title: '영상통화 음소거 확인',
    category: '메뉴·UI',
    description:
      '영상통화 중 음소거 버튼의 음성 차단과 영상 유지 동작을 확인합니다.',
    xp: 20,
    blocks: [
      {
        id: 'mute-connect',
        label: 'A단말과 B단말 사이에 영상통화를 연결한다.',
      },
      {
        id: 'mute-on',
        label: 'A단말에서 음소거 버튼을 선택한다.',
      },
      {
        id: 'mute-wait',
        label:
          '20초 이상 대기하며 상대 단말에 음성이 들리지 않는지 확인한다.',
      },
      {
        id: 'mute-video',
        label: '음소거 상태에서도 영상이 계속 표시되는지 확인한다.',
      },
      {
        id: 'mute-off',
        label:
          '음소거를 해제하고 상대 단말에 음성이 다시 들리는지 확인한다.',
      },
    ],
  },
];

export const suggestedQuestions = [
  'REGISTER 등록 흐름을 설명해줘.',
  '401 Unauthorized 뒤에는 무엇을 확인해?',
  'INVITE와 SDP는 어떤 관계야?',
  'P-CSCF는 어떤 역할을 해?',
  'Dedicated Bearer와 QCI를 설명해줘.',
  'EVS와 AMR-WB의 차이가 뭐야?',
  'H.264와 H.265의 차이가 뭐야?',
  'DSDS에서 통화 테스트 포인트를 알려줘.',
  'RSRP가 낮을 때 영상통화에 어떤 영향이 있어?',
  'Video Bitrate는 어떻게 확인해?',
];