import type { Term } from './types';

export const categories = [
  '통신 기초',
  'SIP',
  'RTP',
  'IMS',
  'LTE / 5G',
  'Wireshark',
  'XCAL',
  'ADB / Logcat',
  '음성통화 QA',
  '영상통화 QA',
  'TC 작성법',
];

type TermSeed = [
  id: string,
  term: string,
  fullName: string,
  category: Term['category'],
  simple: string,
  practical: string,
  example: string,
];

const termSeeds: TermSeed[] = [
  // ─────────────────────────────────────────────
  // 통신 기초
  // ─────────────────────────────────────────────
  [
    'voip',
    'VoIP',
    'Voice over Internet Protocol',
    '통신 기초',
    '인터넷망을 이용해 음성을 전달하는 통화 기술이에요.',
    '음성을 디지털 데이터로 변환한 뒤 IP 패킷 형태로 전달합니다.',
    '인터넷 전화, 메신저 음성통화 등이 VoIP 기술을 사용합니다.',
  ],
  [
    'volte',
    'VoLTE',
    'Voice over LTE',
    '통신 기초',
    'LTE 데이터망을 이용해 음성통화를 제공하는 기술이에요.',
    'IMS와 SIP를 이용해 통화를 연결하고 RTP로 음성을 전달합니다.',
    'LTE 상태에서 음성통화를 발신하고 IMS 메시지를 확인합니다.',
  ],
  [
    'vonr',
    'VoNR',
    'Voice over New Radio',
    '통신 기초',
    '5G SA망에서 제공하는 음성통화 기술이에요.',
    '단말이 LTE로 내려가지 않고 5G NR망에서 IMS 음성통화를 처리합니다.',
    '5G SA 상태에서 발신 후 LTE 전환 없이 통화가 유지되는지 확인합니다.',
  ],
  [
    'codec',
    'Codec',
    'Coder-Decoder',
    '통신 기초',
    '음성이나 영상을 압축하고 다시 복원하는 기술이에요.',
    '통화 연결 과정에서 서로 지원하는 코덱을 SDP로 협상합니다.',
    'AMR-WB, EVS, H.264 등이 통화에서 사용되는 코덱입니다.',
  ],
  [
    'dtmf',
    'DTMF',
    'Dual-Tone Multi-Frequency',
    '통신 기초',
    '전화 키패드를 누를 때 두 개의 주파수를 조합해 입력을 전달하는 방식이에요.',
    'ARS 번호 입력 검증 시 RFC 4733, SIP INFO, In-band 전달 여부를 확인합니다.',
    '통화 중 1번을 눌렀을 때 ARS가 정상적으로 인식하는지 확인합니다.',
  ],
  [
    'latency',
    'Latency',
    'Network Latency',
    '통신 기초',
    '데이터가 상대방에게 전달될 때까지 걸리는 지연 시간이에요.',
    '지연 시간이 길면 상대방의 말이 늦게 들리거나 대화가 겹칠 수 있습니다.',
    '말한 뒤 상대방 단말에서 들릴 때까지의 시간을 확인합니다.',
  ],
  [
    'jitter',
    'Jitter',
    'Packet Delay Variation',
    '통신 기초',
    '패킷 도착 시간의 간격이 일정하지 않은 현상이에요.',
    '지터가 높으면 음성이 끊기거나 영상이 순간적으로 멈출 수 있습니다.',
    'Wireshark의 RTP Stream Analysis에서 Jitter 값을 확인합니다.',
  ],
  [
    'packet-loss',
    'Packet Loss',
    'Packet Loss',
    '통신 기초',
    '전송 중 일부 네트워크 패킷이 유실되는 현상이에요.',
    '패킷 손실이 증가하면 음성 끊김, 로봇음, 영상 깨짐이 발생할 수 있습니다.',
    'RTP Sequence Number가 연속적이지 않은 구간을 확인합니다.',
  ],
  [
    'mos',
    'MOS',
    'Mean Opinion Score',
    '통신 기초',
    '사용자가 느끼는 통화 음질을 점수로 표현한 값이에요.',
    '일반적으로 지연, 지터, 패킷 손실, 코덱 등의 영향을 받습니다.',
    '음질 측정 결과에서 MOS 점수가 기준 이상인지 확인합니다.',
  ],

  // ─────────────────────────────────────────────
  // SIP
  // ─────────────────────────────────────────────
  [
    'sip',
    'SIP',
    'Session Initiation Protocol',
    'SIP',
    '인터넷 전화의 연결과 종료를 관리하는 통신 규칙이에요.',
    'INVITE, ACK, BYE 등의 메시지를 이용해 음성·영상 세션을 설정하고 종료합니다.',
    '발신자가 통화를 시작하면 INVITE 메시지가 전송됩니다.',
  ],
  [
    'invite',
    'INVITE',
    'SIP INVITE Request',
    'SIP',
    '새로운 통화를 시작하거나 통화 상태를 변경할 때 보내는 요청이에요.',
    'SDP를 포함해 코덱, 미디어 주소, 포트 등의 정보를 제안할 수 있습니다.',
    'INVITE → 100 Trying → 180 Ringing → 200 OK → ACK',
  ],
  [
    '100-trying',
    '100 Trying',
    'SIP 100 Trying Response',
    'SIP',
    'INVITE 요청을 수신해 처리 중이라는 임시 응답이에요.',
    '발신 측이 동일한 INVITE를 불필요하게 반복 전송하지 않도록 알려줍니다.',
    'INVITE 전송 직후 100 Trying 응답이 수신되는지 확인합니다.',
  ],
  [
    '180-ringing',
    '180 Ringing',
    'SIP 180 Ringing Response',
    'SIP',
    '상대방 단말에서 벨이 울리고 있다는 임시 응답이에요.',
    '발신 단말은 이 응답을 기준으로 통화 연결음을 재생할 수 있습니다.',
    '수신 단말에 착신 화면이 표시될 때 180 Ringing을 확인합니다.',
  ],
  [
    '183-session-progress',
    '183 Session Progress',
    'SIP 183 Session Progress Response',
    'SIP',
    '통화가 연결되기 전 미디어 처리가 진행 중임을 알리는 응답이에요.',
    'SDP가 포함되면 Early Media 경로를 설정하는 데 사용될 수 있습니다.',
    '통화 연결 전 안내 음성이 들릴 때 183 응답과 RTP를 확인합니다.',
  ],
  [
    '200-ok',
    '200 OK',
    'SIP 200 OK Response',
    'SIP',
    'SIP 요청이 정상적으로 처리되었다는 성공 응답이에요.',
    'INVITE에 대한 200 OK에는 최종 코덱과 미디어 정보가 포함될 수 있습니다.',
    '수신자가 전화를 받으면 INVITE에 대한 200 OK가 전송됩니다.',
  ],
  [
    'ack',
    'ACK',
    'Acknowledgement',
    'SIP',
    '통화 연결 응답을 잘 받았다고 확인하는 메시지예요.',
    'INVITE의 200 OK 이후 ACK가 전달되면 기본 통화 연결 절차가 완성됩니다.',
    '200 OK를 받은 발신 측이 ACK를 전송합니다.',
  ],
  [
    'bye',
    'BYE',
    'SIP BYE Request',
    'SIP',
    '연결된 통화를 종료할 때 사용하는 SIP 요청이에요.',
    'BYE를 받은 상대방은 일반적으로 200 OK로 응답합니다.',
    '발신자가 통화 종료 버튼을 누르면 BYE가 전송됩니다.',
  ],
  [
    'cancel',
    'CANCEL',
    'SIP CANCEL Request',
    'SIP',
    '아직 연결되지 않은 통화 요청을 취소할 때 사용하는 메시지예요.',
    'INVITE가 최종 응답을 받기 전에 발신자가 통화를 취소하면 사용됩니다.',
    '상대방이 받기 전에 종료 버튼을 누르면 CANCEL이 전송될 수 있습니다.',
  ],
  [
    'register',
    'REGISTER',
    'SIP REGISTER Request',
    'SIP',
    '단말의 현재 위치와 접속 정보를 통신망에 등록하는 요청이에요.',
    'IMS 등록 과정에서 단말이 SIP 서버에 자신의 Contact 정보를 등록합니다.',
    '비행기 모드 해제 후 REGISTER 메시지가 정상적으로 처리되는지 확인합니다.',
  ],
  [
    'sdp',
    'SDP',
    'Session Description Protocol',
    'SIP',
    '통화에서 사용할 음성·영상 조건을 설명하는 정보예요.',
    'IP 주소, 포트, 코덱, Payload Type, 미디어 방향 등을 포함할 수 있습니다.',
    'INVITE와 200 OK의 SDP에서 코덱과 RTP 포트를 비교합니다.',
  ],
  [
    'p-access-network-info',
    'P-Access-Network-Info',
    'P-Access-Network-Info Header',
    'SIP',
    '단말이 현재 접속 중인 네트워크 방식과 위치 정보를 전달하는 SIP 헤더예요.',
    'LTE, Wi-Fi 등의 접속 방식과 MCC, MNC, TAC, Cell Identity 정보가 포함될 수 있습니다.',
    'P-Access-Network-Info: 3GPP-E-UTRAN-FDD; utran-cell-id-3gpp=...',
  ],
  [
    'call-id',
    'Call-ID',
    'SIP Call Identifier',
    'SIP',
    '하나의 SIP 통화나 세션을 구분하기 위한 고유한 값이에요.',
    '같은 통화에 속하는 SIP 메시지는 일반적으로 동일한 Call-ID를 사용합니다.',
    'INVITE와 BYE의 Call-ID가 동일한지 확인합니다.',
  ],
  [
    'cseq',
    'CSeq',
    'Command Sequence',
    'SIP',
    'SIP 요청의 순서와 요청 종류를 구분하는 헤더예요.',
    '숫자와 메서드명으로 구성되며 재전송이나 새로운 요청을 구분할 때 사용됩니다.',
    'CSeq: 1 INVITE, CSeq: 2 BYE',
  ],

  // ─────────────────────────────────────────────
  // RTP
  // ─────────────────────────────────────────────
  [
    'rtp',
    'RTP',
    'Real-time Transport Protocol',
    'RTP',
    '통화 중 실제 음성과 영상 데이터를 전달하는 규칙이에요.',
    'SIP로 세션을 설정한 뒤 음성·영상 미디어 패킷 전달에 사용됩니다.',
    '통화는 연결됐지만 음성이 없을 때 RTP 흐름을 확인합니다.',
  ],
  [
    'rtcp',
    'RTCP',
    'RTP Control Protocol',
    'RTP',
    'RTP 통신의 품질과 상태 정보를 전달하는 제어 프로토콜이에요.',
    '패킷 손실, 지터, 송수신 패킷 수 등의 통계 정보를 교환합니다.',
    'RTCP Receiver Report에서 Packet Loss와 Jitter를 확인합니다.',
  ],
  [
    'payload-type',
    'Payload Type',
    'RTP Payload Type',
    'RTP',
    'RTP 패킷에 어떤 코덱이나 미디어 형식이 들어 있는지 나타내는 값이에요.',
    'SDP의 rtpmap 정보와 RTP 헤더의 Payload Type 값이 일치해야 합니다.',
    'a=rtpmap:96 AMR-WB/16000',
  ],
  [
    'dpt',
    'DPT',
    'Dynamic Payload Type',
    'RTP',
    '통화마다 코덱과 미디어 형식을 동적으로 지정하는 Payload Type이에요.',
    'SDP의 rtpmap 속성을 통해 특정 번호와 코덱을 연결합니다.',
    'Payload Type 96을 H.264 영상 코덱으로 협상할 수 있습니다.',
  ],
  [
    'sequence-number',
    'Sequence Number',
    'RTP Sequence Number',
    'RTP',
    'RTP 패킷의 전송 순서를 구분하는 번호예요.',
    '수신 측은 Sequence Number를 이용해 패킷 유실과 순서 변경을 확인합니다.',
    'Sequence Number가 100, 101, 103이면 102번 패킷 유실을 의심합니다.',
  ],
  [
    'rtp-timestamp',
    'RTP Timestamp',
    'RTP Timestamp',
    'RTP',
    '음성이나 영상이 재생되어야 하는 시간 순서를 나타내는 값이에요.',
    '수신 측에서 미디어 재생 시점과 동기화를 맞추는 데 사용됩니다.',
    '영상 프레임의 재생 순서를 RTP Timestamp로 확인합니다.',
  ],
  [
    'ssrc',
    'SSRC',
    'Synchronization Source Identifier',
    'RTP',
    'RTP 미디어 송신자를 구분하기 위한 식별자예요.',
    '한 통화에서 음성 또는 영상 송신 소스별로 서로 다른 SSRC를 사용할 수 있습니다.',
    '카메라 전환 후 영상 SSRC가 변경되는지 확인합니다.',
  ],
  [
    'srtp',
    'SRTP',
    'Secure Real-time Transport Protocol',
    'RTP',
    'RTP 음성·영상 데이터를 암호화해서 전달하는 방식이에요.',
    '미디어 도청이나 변조를 방지하기 위해 RTP에 보안 기능을 추가합니다.',
    '암호화된 통화에서는 Wireshark에서 음성 내용을 바로 재생하기 어렵습니다.',
  ],
  [
    'amr-wb',
    'AMR-WB',
    'Adaptive Multi-Rate Wideband',
    'RTP',
    'VoLTE에서 자주 사용하는 광대역 음성 코덱이에요.',
    '일반 음성보다 넓은 주파수 대역을 사용해 비교적 선명한 음질을 제공합니다.',
    'SDP에 AMR-WB 코덱이 포함되어 있는지 확인합니다.',
  ],
  [
    'evs',
    'EVS',
    'Enhanced Voice Services',
    'RTP',
    'VoLTE와 VoNR에서 사용할 수 있는 고품질 음성 코덱이에요.',
    '음성 대역폭과 네트워크 상황에 따라 높은 음질과 안정성을 제공합니다.',
    'EVS 지원 단말끼리 통화할 때 SDP 코덱 협상 결과를 확인합니다.',
  ],

  // ─────────────────────────────────────────────
  // IMS
  // ─────────────────────────────────────────────
  [
    'ims',
    'IMS',
    'IP Multimedia Subsystem',
    'IMS',
    '통신사의 음성·영상통화와 멀티미디어 서비스를 처리하는 네트워크 구조예요.',
    'VoLTE와 VoNR 서비스에서 SIP 등록, 통화 연결, 서비스 제어를 담당합니다.',
    '단말이 IMS에 등록되어야 VoLTE 발신이 정상적으로 진행됩니다.',
  ],
  [
    'pcscf',
    'P-CSCF',
    'Proxy-Call Session Control Function',
    'IMS',
    '단말이 IMS망에 접속할 때 만나는 최초의 SIP 접속점이에요.',
    '단말과 IMS망 사이에서 SIP 메시지를 전달하고 보안 및 정책 처리를 지원합니다.',
    '단말의 REGISTER와 INVITE 메시지가 P-CSCF를 통해 전달됩니다.',
  ],
  [
    'scscf',
    'S-CSCF',
    'Serving-Call Session Control Function',
    'IMS',
    'IMS 가입자의 등록과 통화 세션을 핵심적으로 제어하는 서버예요.',
    '사용자 인증 상태와 서비스 정책을 기반으로 SIP 세션을 처리합니다.',
    'IMS 등록 후 가입자에게 할당된 S-CSCF가 통화 요청을 처리합니다.',
  ],
  [
    'sbc',
    'SBC',
    'Session Border Controller',
    'IMS',
    '서로 다른 통신망 사이의 SIP와 미디어 연결을 보호하고 제어하는 장비예요.',
    '보안, 주소 변환, 코덱 정책, 망 간 연동 등의 역할을 수행할 수 있습니다.',
    '타 통신사와의 통화에서 SIP 주소나 SDP 정보가 변경되는지 확인합니다.',
  ],

  // ─────────────────────────────────────────────
  // LTE / 5G
  // ─────────────────────────────────────────────
  [
    '3gpp-e-utran',
    '3GPP-E-UTRAN',
    '3GPP Evolved Universal Terrestrial Radio Access Network',
    'LTE / 5G',
    '4G LTE 무선 접속망을 나타내는 값이에요.',
    'P-Access-Network-Info 등의 헤더에서 단말의 LTE 접속 방식을 표현할 수 있습니다.',
    'access-type=3GPP-E-UTRAN-FDD',
  ],
  [
    'mcc',
    'MCC',
    'Mobile Country Code',
    'LTE / 5G',
    '이동통신망에서 국가를 구분하는 코드예요.',
    'MNC와 조합해 단말이 접속한 이동통신망을 식별합니다.',
    '한국의 이동통신망 정보에서 MCC 값으로 450이 표시될 수 있습니다.',
  ],
  [
    'mnc',
    'MNC',
    'Mobile Network Code',
    'LTE / 5G',
    '한 국가 안에서 이동통신사를 구분하는 코드예요.',
    'MCC와 MNC를 결합해 PLMN을 구성합니다.',
    'MCC 450과 특정 MNC 조합으로 접속 통신사를 구분합니다.',
  ],
  [
    'plmn',
    'PLMN',
    'Public Land Mobile Network',
    'LTE / 5G',
    'MCC와 MNC로 구성되는 이동통신망 식별 정보예요.',
    '로밍이나 망 선택 상태를 확인할 때 현재 등록된 PLMN을 확인합니다.',
    '단말이 예상한 통신사의 PLMN에 등록되었는지 확인합니다.',
  ],
  [
    'tac',
    'TAC',
    'Tracking Area Code',
    'LTE / 5G',
    'LTE와 5G에서 단말의 위치 추적 영역을 구분하는 코드예요.',
    '단말이 다른 Tracking Area로 이동하면 위치 갱신 절차가 발생할 수 있습니다.',
    '이동 중 TAC가 변경된 시점과 통화 상태를 함께 확인합니다.',
  ],
  [
    'cell-identity',
    'Cell Identity',
    'Cell Identifier',
    'LTE / 5G',
    '단말이 접속한 기지국 셀을 구분하는 식별 정보예요.',
    '기지국 전체가 아니라 단말이 실제로 접속한 셀 또는 안테나 영역을 구분합니다.',
    '통화 끊김 시점 전후의 Cell Identity 변경 여부를 확인합니다.',
  ],
  [
    'rsrp',
    'RSRP',
    'Reference Signal Received Power',
    'LTE / 5G',
    '단말이 수신하는 LTE·5G 기준 신호의 세기를 나타내는 값이에요.',
    '값이 지나치게 낮으면 통화 품질 저하나 핸드오버 실패가 발생할 수 있습니다.',
    '통화 끊김 시점의 RSRP 값이 급격히 낮아졌는지 확인합니다.',
  ],
  [
    'rsrq',
    'RSRQ',
    'Reference Signal Received Quality',
    'LTE / 5G',
    '수신 신호의 품질을 나타내는 값이에요.',
    '신호 세기가 충분해도 간섭이 많으면 RSRQ가 좋지 않을 수 있습니다.',
    '음성 끊김 발생 구간의 RSRQ 변화를 확인합니다.',
  ],
  [
    'sinr',
    'SINR',
    'Signal to Interference plus Noise Ratio',
    'LTE / 5G',
    '원하는 신호와 간섭·잡음의 비율을 나타내는 값이에요.',
    'SINR이 높을수록 일반적으로 데이터 전송 품질이 좋아집니다.',
    '영상통화 화질 저하 시 SINR과 전송률을 함께 확인합니다.',
  ],
  [
    'handover',
    'Handover',
    'Network Handover',
    'LTE / 5G',
    '통화나 데이터 연결을 유지하면서 다른 기지국이나 망으로 이동하는 절차예요.',
    '이동 중 셀 변경 또는 Wi-Fi와 이동통신망 전환 시 통화 연속성을 확인합니다.',
    '차량 이동 중 기지국이 변경되어도 통화가 끊기지 않는지 확인합니다.',
  ],
  [
    'srvcc',
    'SRVCC',
    'Single Radio Voice Call Continuity',
    'LTE / 5G',
    'VoLTE 통화를 기존 3G 또는 2G 음성망으로 넘겨 통화를 유지하는 기술이에요.',
    'LTE 커버리지를 벗어날 때 통화가 끊기지 않도록 망 전환을 수행합니다.',
    'VoLTE 통화 중 LTE 신호가 약해질 때 통화 유지 여부를 확인합니다.',
  ],
  [
    'eps-fallback',
    'EPS Fallback',
    'Evolved Packet System Fallback',
    'LTE / 5G',
    '5G에서 음성통화를 위해 LTE망으로 전환하는 절차예요.',
    'VoNR을 사용할 수 없는 환경에서 5G 단말이 LTE로 이동해 VoLTE 통화를 진행합니다.',
    '5G 상태에서 발신했을 때 LTE로 전환된 후 통화가 연결되는지 확인합니다.',
  ],

  // ─────────────────────────────────────────────
  // Wireshark
  // ─────────────────────────────────────────────
  [
    'wireshark',
    'Wireshark',
    'Wireshark Network Protocol Analyzer',
    'Wireshark',
    '네트워크 패킷을 눈으로 확인하는 분석 도구예요.',
    'SIP, RTP, TCP, UDP 등의 필터를 이용해 통화 시그널링과 미디어 흐름을 분석합니다.',
    '표시 필터에 sip를 입력해 SIP 메시지만 확인합니다.',
  ],
  [
    'display-filter',
    'Display Filter',
    'Wireshark Display Filter',
    'Wireshark',
    '이미 수집된 패킷 중 원하는 패킷만 화면에 표시하는 조건이에요.',
    'SIP, RTP, 특정 IP 주소나 포트 조건을 조합해 분석 범위를 줄입니다.',
    'sip || rtp 또는 ip.addr == 10.0.0.1',
  ],
  [
    'voip-calls',
    'VoIP Calls',
    'Wireshark VoIP Calls',
    'Wireshark',
    'Wireshark에서 SIP 통화 목록과 흐름을 확인하는 기능이에요.',
    '통화별 발신자, 수신자, 시작 시간, 종료 상태와 Flow Sequence를 확인할 수 있습니다.',
    'Telephony → VoIP Calls에서 분석할 통화를 선택합니다.',
  ],
  [
    'rtp-stream-analysis',
    'RTP Stream Analysis',
    'Wireshark RTP Stream Analysis',
    'Wireshark',
    'RTP 패킷의 손실률, 지터, 순서 오류 등을 분석하는 기능이에요.',
    '음성 끊김이나 영상 깨짐 원인을 확인할 때 사용합니다.',
    'Telephony → RTP → RTP Streams에서 스트림을 선택합니다.',
  ],

  // ─────────────────────────────────────────────
  // XCAL
  // ─────────────────────────────────────────────
  [
    'xcal',
    'XCAL',
    'Mobile Network Analysis Tool',
    'XCAL',
    '단말과 이동통신망의 동작을 수집하고 분석하는 통신 로그 도구예요.',
    'SIP, LTE·5G Signaling, 무선 신호, 통화 이벤트 등을 시간 순서대로 확인합니다.',
    '통화 실패 시 SIP Message와 Signaling Message를 함께 분석합니다.',
  ],
  [
    'sip-message',
    'SIP Message',
    'Session Initiation Protocol Message',
    'XCAL',
    '통화 연결과 종료 과정에서 단말과 IMS망이 주고받는 메시지예요.',
    'INVITE, REGISTER, ACK, BYE 및 응답 코드를 확인할 수 있습니다.',
    '통화 실패 구간에서 INVITE 이후 어떤 응답이 수신되었는지 확인합니다.',
  ],
  [
    'signaling-message',
    'Signaling Message',
    'Network Signaling Message',
    'XCAL',
    '단말과 통신망이 연결 상태와 제어 정보를 주고받는 메시지예요.',
    '망 등록, 셀 선택, 핸드오버, 베어러 설정 등의 절차를 분석합니다.',
    '통화 끊김 직전에 핸드오버 실패 메시지가 있었는지 확인합니다.',
  ],
  [
    'ppp-frame',
    'PPP Frame',
    'Point-to-Point Protocol Frame',
    'XCAL',
    '두 장치 사이에서 데이터를 전달하기 위한 PPP 형식의 프레임이에요.',
    '일부 단말 로그 환경에서 데이터 통신이나 진단 인터페이스 메시지를 확인할 때 사용됩니다.',
    '문제 발생 시점 전후의 PPP Frame 흐름과 오류 여부를 확인합니다.',
  ],
  [
    'te-timer',
    'TE',
    'Timer Expiry',
    'XCAL',
    '타이머가 만료되는 시간이나 이벤트를 나타내는 용어로 사용될 수 있어요.',
    'TE의 정확한 의미와 단위는 XCAL 스크립트 또는 사내 테스트 환경에 따라 달라질 수 있습니다.',
    'TE 발생 시점 이후 재전송 또는 실패 처리가 시작되는지 확인합니다.',
  ],
  [
    't2-timer',
    'T2',
    'Second Retransmission Timer',
    'XCAL',
    '두 번째 재전송까지 대기하는 시간을 나타내는 용어로 사용될 수 있어요.',
    '프로토콜 또는 XCAL 시나리오별로 T2의 의미와 기준값이 다를 수 있습니다.',
    '첫 전송 실패 후 T2 시간만큼 대기하고 재전송하는지 확인합니다.',
  ],
  [
    'tf',
    'TF',
    'Transmission Factor / Failure Counter',
    'XCAL',
    '재전송 횟수 제한이나 전송 주기 배수를 나타내는 값으로 사용될 수 있어요.',
    'TF는 표준 공통 명칭이 아닐 수 있으므로 사용하는 장비와 시나리오 정의를 확인해야 합니다.',
    'TF 제한 횟수를 초과했을 때 실패 이벤트가 기록되는지 확인합니다.',
  ],
  [
    'apcs-dm-server',
    'APCS-DM Server',
    'AP Control / Device Management Server',
    'XCAL',
    '무선 AP나 단말 설정을 중앙에서 관리하는 서버를 의미할 수 있어요.',
    '조직이나 솔루션별 내부 명칭일 수 있으므로 실제 역할은 사내 문서와 시스템 구성을 확인해야 합니다.',
    'AP 설정 변경 후 APCS-DM 서버와 동기화되는지 확인합니다.',
  ],

  // ─────────────────────────────────────────────
  // ADB / Logcat
  // ─────────────────────────────────────────────
  [
    'adb',
    'ADB',
    'Android Debug Bridge',
    'ADB / Logcat',
    '컴퓨터에서 안드로이드 단말을 제어하고 로그를 확인하는 도구예요.',
    '앱 실행, 파일 전송, 셸 명령 실행, 로그 수집 등에 사용합니다.',
    'adb devices 명령으로 연결된 단말을 확인합니다.',
  ],
  [
    'logcat',
    'Logcat',
    'Android Logcat',
    'ADB / Logcat',
    '안드로이드 시스템과 앱에서 발생한 로그를 시간 순서대로 확인하는 기능이에요.',
    '통화 앱, Telecom, IMS, RIL 관련 오류와 상태 변화를 분석할 수 있습니다.',
    'adb logcat -v time 명령으로 로그를 수집합니다.',
  ],
  [
    'radio-buffer',
    'Radio Buffer',
    'Android Radio Log Buffer',
    'ADB / Logcat',
    '안드로이드의 무선통신과 모뎀 관련 로그가 저장되는 버퍼예요.',
    'RIL, 망 등록, 통화 상태, 데이터 연결 관련 로그를 확인할 때 사용합니다.',
    'adb logcat -b radio -v time',
  ],
  [
    'ril',
    'RIL',
    'Radio Interface Layer',
    'ADB / Logcat',
    '안드로이드 시스템과 단말 모뎀 사이의 통신을 연결하는 계층이에요.',
    '발신, 수신, 망 등록, 데이터 연결 등의 명령과 응답을 전달합니다.',
    '통화 발신 시 RIL 관련 Dial 요청과 상태 변경 로그를 확인합니다.',
  ],
  [
    'dumpsys-telecom',
    'dumpsys telecom',
    'Android Telecom Service Dump',
    'ADB / Logcat',
    '현재 안드로이드 통화 서비스의 상태 정보를 출력하는 명령이에요.',
    '진행 중인 통화, ConnectionService, Call 상태 등을 확인할 수 있습니다.',
    'adb shell dumpsys telecom',
  ],
  [
    'bugreport',
    'Bugreport',
    'Android Bug Report',
    'ADB / Logcat',
    '단말의 시스템 상태와 다양한 로그를 한 번에 수집한 진단 자료예요.',
    '재현 직후 수집하면 통화 문제 발생 시점의 시스템 상태를 분석하는 데 도움이 됩니다.',
    'adb bugreport bugreport.zip',
  ],

  // ─────────────────────────────────────────────
  // 음성통화 QA
  // ─────────────────────────────────────────────
  [
    'mo-call',
    'MO',
    'Mobile Originated Call',
    '음성통화 QA',
    '테스트 단말에서 상대방에게 발신하는 통화예요.',
    '발신 단말 기준의 SIP 흐름, 통화 연결 시간, 음성 상태를 확인합니다.',
    'A 단말에서 B 단말로 전화를 걸어 MO 통화를 검증합니다.',
  ],
  [
    'mt-call',
    'MT',
    'Mobile Terminated Call',
    '음성통화 QA',
    '상대방이 테스트 단말로 발신해 수신하는 통화예요.',
    '수신 화면, 벨소리, 진동, 응답, 수신 후 음성 상태를 확인합니다.',
    'B 단말에서 A 단말로 전화해 A 단말의 MT 동작을 검증합니다.',
  ],
  [
    'call-setup-time',
    'Call Setup Time',
    'Call Setup Time',
    '음성통화 QA',
    '통화 발신 후 상대방 벨 또는 통화 연결까지 걸리는 시간이에요.',
    '발신 버튼 선택 시점부터 180 Ringing 또는 200 OK까지의 시간을 확인할 수 있습니다.',
    '통화 연결 시간이 기준보다 지나치게 길지 않은지 확인합니다.',
  ],
  [
    'one-way-audio',
    'One-way Audio',
    'One-way Audio Issue',
    '음성통화 QA',
    '한쪽 음성만 전달되고 반대쪽 음성은 들리지 않는 현상이에요.',
    'RTP 주소, 포트, 방화벽, 코덱, 음소거 상태, 오디오 경로를 확인합니다.',
    'A의 목소리는 B에서 들리지만 B의 목소리가 A에서 들리지 않습니다.',
  ],
  [
    'audio-route',
    'Audio Route',
    'Audio Output Route',
    '음성통화 QA',
    '통화 음성이 출력되는 경로를 의미해요.',
    '수화부, 스피커, 유선 이어폰, 블루투스 장치 전환을 확인합니다.',
    '블루투스 연결 해제 후 음성이 수화부로 정상 전환되는지 확인합니다.',
  ],
  [
    'hold-resume',
    'Hold / Resume',
    'Call Hold and Resume',
    '음성통화 QA',
    '통화를 잠시 보류한 뒤 다시 재개하는 기능이에요.',
    '보류 중 미디어 방향 변경과 재개 후 양방향 음성 복구 여부를 확인합니다.',
    '통화 보류 후 재개했을 때 음성이 정상적으로 들리는지 확인합니다.',
  ],

  // ─────────────────────────────────────────────
  // 영상통화 QA
  // ─────────────────────────────────────────────
  [
    'video-upgrade',
    'Video Upgrade / Downgrade',
    'Video Call Upgrade and Downgrade',
    '영상통화 QA',
    '음성통화와 영상통화 사이를 전환하는 기능이에요.',
    'Re-INVITE 또는 UPDATE 과정에서 SDP 미디어 조건이 정상적으로 변경되는지 확인합니다.',
    '음성통화 중 영상통화로 전환한 뒤 다시 음성통화로 복귀합니다.',
  ],
  [
    'one-way-video',
    'One-way Video',
    'One-way Video Issue',
    '영상통화 QA',
    '한쪽 영상만 보이고 상대 방향 영상은 보이지 않는 현상이에요.',
    '영상 RTP 주소, 코덱, 카메라 상태, 미디어 방향 속성을 확인합니다.',
    'A는 B의 화면을 보지만 B는 A의 화면을 볼 수 없습니다.',
  ],
  [
    'video-freeze',
    'Freeze',
    'Video Freeze',
    '영상통화 QA',
    '영상 화면이 특정 장면에서 멈추는 현상이에요.',
    '패킷 손실, 지터, 네트워크 전환, 디코딩 오류 등을 확인합니다.',
    '이동 중 영상은 멈췄지만 음성은 계속 들리는지 확인합니다.',
  ],
  [
    'pixelation',
    'Pixelation',
    'Video Pixelation',
    '영상통화 QA',
    '영상이 모자이크처럼 깨지거나 네모난 블록으로 보이는 현상이에요.',
    '패킷 손실, 낮은 Bitrate, 코덱 오류가 원인이 될 수 있습니다.',
    '약전계 환경에서 영상 깨짐이 반복적으로 발생하는지 확인합니다.',
  ],
  [
    'av-sync',
    'A/V Sync',
    'Audio and Video Synchronization',
    '영상통화 QA',
    '음성과 영상의 재생 시점이 서로 맞는 상태를 의미해요.',
    '입 모양과 음성이 어긋나면 RTP Timestamp와 지연 시간을 확인합니다.',
    '상대방의 입 모양보다 음성이 늦게 들리는지 확인합니다.',
  ],
  [
    'bitrate',
    'Bitrate',
    'Media Bitrate',
    '영상통화 QA',
    '1초 동안 전송되는 음성 또는 영상 데이터의 양이에요.',
    '네트워크 상태에 따라 영상 Bitrate가 조정되며 화질에 영향을 줍니다.',
    '약전계에서 Bitrate가 낮아지고 화질이 조정되는지 확인합니다.',
  ],
  [
    'frame-rate',
    'Frame Rate',
    'Frames Per Second',
    '영상통화 QA',
    '1초 동안 표시되는 영상 프레임의 수예요.',
    'Frame Rate가 낮아지면 움직임이 끊겨 보일 수 있습니다.',
    '영상통화 중 FPS가 급격하게 떨어지는 구간을 확인합니다.',
  ],
  [
    'ice',
    'ICE',
    'Interactive Connectivity Establishment',
    '영상통화 QA',
    '두 단말이 통신할 수 있는 네트워크 경로를 찾는 절차예요.',
    '여러 Candidate를 수집하고 연결 가능한 주소와 포트 조합을 선택합니다.',
    '직접 연결이 불가능하면 TURN 중계 경로가 선택될 수 있습니다.',
  ],
  [
    'stun',
    'STUN',
    'Session Traversal Utilities for NAT',
    '영상통화 QA',
    '단말이 외부에서 보이는 IP 주소와 포트를 확인하도록 돕는 기술이에요.',
    'NAT 환경에서 Server Reflexive Candidate를 생성하는 데 사용됩니다.',
    'STUN 서버를 통해 외부 IP와 포트 정보를 획득합니다.',
  ],
  [
    'turn',
    'TURN',
    'Traversal Using Relays around NAT',
    '영상통화 QA',
    '직접 연결이 어려울 때 미디어를 중계 서버를 통해 전달하는 기술이에요.',
    '방화벽이나 NAT로 P2P 연결이 불가능한 경우 Relay Candidate를 사용합니다.',
    '회사 Wi-Fi에서 직접 연결이 실패해 TURN 서버를 경유합니다.',
  ],
  [
    'candidate-attribute',
    'Candidate Attribute',
    'ICE Candidate Attribute',
    '영상통화 QA',
    '통신에 사용할 수 있는 IP 주소와 포트 등 네트워크 연결 후보의 속성이에요.',
    'Candidate Type, IP, Port, Transport, Priority 등의 정보가 포함됩니다.',
    'a=candidate:1 1 UDP 2130706431 192.168.0.2 50000 typ host',
  ],

  // ─────────────────────────────────────────────
  // TC 작성법
  // ─────────────────────────────────────────────
  [
    'precondition',
    'Precondition',
    'Test Precondition',
    'TC 작성법',
    '테스트를 시작하기 전에 준비되어야 하는 조건이에요.',
    '단말 상태, 유심, 네트워크 설정, 앱 버전 등을 명확히 작성합니다.',
    'A·B 단말 모두 VoLTE 등록 상태이며 LTE에 연결되어 있어야 합니다.',
  ],
  [
    'test-steps',
    'Test Steps',
    'Test Procedure',
    'TC 작성법',
    '테스트를 재현하기 위해 순서대로 수행하는 절차예요.',
    '누가 수행해도 같은 결과가 나오도록 동작과 조건을 구체적으로 작성합니다.',
    '1. 전화 앱 실행 → 2. 번호 입력 → 3. 영상통화 버튼 선택',
  ],
  [
    'expected-result',
    'Expected Result',
    'Expected Test Result',
    'TC 작성법',
    '정상 동작했을 때 나타나야 하는 결과예요.',
    '화면, 음성, 영상, 로그, 상태 변화 등 확인 가능한 기준으로 작성합니다.',
    '영상통화가 연결되고 양방향 음성과 영상이 정상적으로 전달되어야 합니다.',
  ],
  [
    'actual-result',
    'Actual Result',
    'Actual Test Result',
    'TC 작성법',
    '테스트를 수행했을 때 실제로 나타난 결과예요.',
    '주관적인 표현보다 발생 시점, 조건, 화면과 로그를 구체적으로 작성합니다.',
    '통화 연결 5초 후 수신 단말의 영상이 멈추고 음성만 전달됩니다.',
  ],
  [
    'reproducibility',
    'Reproducibility',
    'Issue Reproducibility',
    'TC 작성법',
    '동일한 문제가 반복해서 발생하는 정도예요.',
    '재현 횟수와 전체 시도 횟수를 함께 작성하면 판단하기 쉽습니다.',
    '10회 시도 중 7회 재현되었습니다.',
  ],
  [
    'severity',
    'Severity',
    'Issue Severity',
    'TC 작성법',
    '문제가 서비스 사용에 미치는 영향의 크기예요.',
    '통화 불가, 기능 일부 불가, UI 오류 등 사용자 영향도를 기준으로 판단합니다.',
    '모든 영상통화가 연결되지 않아 높은 Severity로 분류합니다.',
  ],
  [
    'priority',
    'Priority',
    'Issue Priority',
    'TC 작성법',
    '문제를 얼마나 빠르게 수정해야 하는지를 나타내는 우선순위예요.',
    'Severity뿐 아니라 출시 일정, 재현 빈도, 영향 사용자 수를 함께 고려합니다.',
    '출시 필수 기능에서 발생해 높은 Priority로 지정합니다.',
  ],
  [
    'nt',
    'N/T',
    'Not Tested',
    'TC 작성법',
    '필요한 조건이 준비되지 않아 테스트하지 못한 상태예요.',
    '단순히 미수행으로 적지 않고 계정, 단말, 망, 서버 등 구체적인 사유를 작성합니다.',
    'N/T 사유: VoNR 지원 단말 미보유로 테스트하지 못함.',
  ],
];

export const terms: Term[] = termSeeds.map(
  ([id, term, fullName, category, simple, practical, example]) => ({
    id,
    term,
    fullName,
    category,
    simple,
    practical,
    example,
  }),
);

export const callFlow = [
  { id: 'open-app', label: '발신 단말에서 전화 앱을 실행한다.' },
  { id: 'input-number', label: '상대방 번호를 입력한다.' },
  { id: 'tap-call', label: '통화 버튼을 선택한다.' },
  { id: 'send-invite', label: '발신 단말에서 SIP INVITE가 전송된다.' },
  { id: 'receive-ringing', label: '180 Ringing 또는 183 Session Progress를 확인한다.' },
  { id: 'receive-call', label: '수신 단말에서 전화를 받는다.' },
  { id: 'receive-ok', label: '수신 측에서 200 OK가 전송된다.' },
  { id: 'send-ack', label: '발신 측에서 ACK를 전송한다.' },
  { id: 'check-audio', label: '양방향 음성이 정상적으로 들리는지 확인한다.' },
  { id: 'check-video', label: '영상통화인 경우 양방향 영상이 정상적으로 보이는지 확인한다.' },
  { id: 'end-call', label: '통화를 종료하고 BYE와 200 OK를 확인한다.' },
];

export const suggestedQuestions = [
  'SIP와 RTP의 차이가 뭐야?',
  'INVITE부터 ACK까지 통화 연결 순서를 설명해줘.',
  '180 Ringing과 183 Session Progress의 차이는 뭐야?',
  'P-Access-Network-Info에서 MCC, MNC, TAC를 어떻게 확인해?',
  '통화는 연결됐는데 음성이 안 들리면 무엇을 확인해야 해?',
  '한쪽 음성만 들리는 One-way Audio 원인을 알려줘.',
  '영상통화 화면이 멈출 때 어떤 로그를 확인해야 해?',
  'Wireshark에서 SIP와 RTP 패킷을 확인하는 방법을 알려줘.',
  'XCAL에서 음성통화 실패 로그를 확인하는 순서를 알려줘.',
  'ADB Logcat에서 통화 관련 로그를 수집하는 명령어를 알려줘.',
  '음성통화 TC 예시를 만들어줘.',
  '영상통화 전환 TC 예시를 만들어줘.',
  '재현 절차와 실제 결과를 QA 형식으로 정리해줘.',
];